#!/bin/bash
#
# Entrypoint for the openfortivpn gateway container.
#
# It reads its configuration from environment variables, pins a route to the
# VPN gateway on the physical uplink, installs a killswitch firewall and then
# keeps an openfortivpn session alive (reconnecting forever).
#
set -uo pipefail

log()  { printf '%s [openfortivpn] %s\n' "$(date '+%Y-%m-%dT%H:%M:%S%z')" "$*"; }
warn() { log "WARN: $*"; }
die()  { log "ERROR: $*"; exit 1; }

is_on() {
    case "${1,,}" in
        on|1|yes|true) return 0 ;;
        *)             return 1 ;;
    esac
}

read_file() {
    [ -n "${1:-}" ] && [ -f "$1" ] && cat "$1"
    return 0
}

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
VPN_HOST="${VPN_HOST:-}"
VPN_PORT="${VPN_PORT:-443}"
VPN_USER="${VPN_USER:-}"
VPN_PASSWORD="${VPN_PASSWORD:-}"
VPN_PASSWORD_FILE="${VPN_PASSWORD_FILE:-}"
VPN_OTP="${VPN_OTP:-}"
VPN_OTP_FILE="${VPN_OTP_FILE:-}"
VPN_REALM="${VPN_REALM:-}"
VPN_TRUSTED_CERT="${VPN_TRUSTED_CERT:-}"
VPN_CLIENT_CERT="${VPN_CLIENT_CERT:-}"
VPN_CLIENT_KEY="${VPN_CLIENT_KEY:-}"
VPN_CA_FILE="${VPN_CA_FILE:-}"
VPN_SNI="${VPN_SNI:-}"
VPN_SET_DNS="${VPN_SET_DNS:-0}"
VPN_PPPD_PEERDNS="${VPN_PPPD_PEERDNS:-1}"
VPN_HALF_INTERNET_ROUTES="${VPN_HALF_INTERNET_ROUTES:-0}"
VPN_INSECURE_SSL="${VPN_INSECURE_SSL:-0}"
VPN_MIN_TLS="${VPN_MIN_TLS:-}"
VPN_FULL_TUNNEL="${VPN_FULL_TUNNEL:-on}"
VPN_RECONNECT_DELAY="${VPN_RECONNECT_DELAY:-5}"
VPN_EXTRA_ARGS="${VPN_EXTRA_ARGS:-}"

FIREWALL_ENABLED="${FIREWALL_ENABLED:-on}"
LAN_IFACE="${LAN_IFACE:-}"
LAN_SUBNET="${LAN_SUBNET:-}"
DNS_SERVERS="${DNS_SERVERS:-}"

CONFIG_FILE="${CONFIG_FILE:-/etc/openfortivpn/config}"

STOPPING=0
VPN_PID=""
CONFIGURED_IFACE=""
UPLINK_DEV=""
UPLINK_GW=""
SERVER_IPS=""
IPT="iptables"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
# Turn a host name into a space separated list of IPv4 addresses.
resolve_ipv4() {
    local host="$1"
    if [[ "$host" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        printf '%s' "$host"
        return 0
    fi
    # Only "Address:" lines carry answers; the "Server:" line and the
    # resolver address (which includes a port) are filtered out.
    nslookup "$host" 2>/dev/null \
        | tr -d '\r' \
        | awk '$1 == "Address:" {print $2} $1 == "Address" {print $3}' \
        | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' \
        | sort -u \
        | paste -sd' ' -
}

detect_uplink() {
    local line
    line="$(ip -4 route show default 2>/dev/null | head -n1)"
    [ -z "$line" ] && return 1
    UPLINK_DEV="$(awk '{for (i=1;i<=NF;i++) if ($i=="dev") {print $(i+1); exit}}' <<<"$line")"
    UPLINK_GW="$(awk '{for (i=1;i<=NF;i++) if ($i=="via") {print $(i+1); exit}}' <<<"$line")"
    [ -n "$UPLINK_DEV" ]
}

current_ppp_iface() {
    ip -o link show 2>/dev/null \
        | awk -F': ' '$2 ~ /^ppp/ {print $2; exit}'
}

iface_has_ipv4() {
    ip -4 addr show "$1" 2>/dev/null | grep -q 'inet '
}

# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------
create_ppp_device() {
    [ -e /dev/ppp ] && return 0
    log "creating /dev/ppp device node"
    mknod /dev/ppp c 108 0 2>/dev/null \
        || warn "could not create /dev/ppp; pass --device=/dev/ppp or run privileged"
}

enable_forwarding() {
    log "enabling IPv4 forwarding"
    echo 1 > /proc/sys/net/ipv4/ip_forward 2>/dev/null \
        || warn "could not enable net.ipv4.ip_forward"
}

write_config() {
    mkdir -p "$(dirname "$CONFIG_FILE")"
    {
        echo "# generated by the openfortivpn entrypoint"
        echo "host = $VPN_HOST"
        echo "port = $VPN_PORT"
        [ -n "$VPN_USER" ]         && echo "username = $VPN_USER"
        [ -n "$VPN_PASSWORD" ]     && echo "password = $VPN_PASSWORD"
        [ -n "$VPN_REALM" ]        && echo "realm = $VPN_REALM"
        [ -n "$VPN_TRUSTED_CERT" ] && echo "trusted-cert = $VPN_TRUSTED_CERT"
        [ -n "$VPN_CLIENT_CERT" ]  && echo "user-cert = $VPN_CLIENT_CERT"
        [ -n "$VPN_CLIENT_KEY" ]   && echo "user-key = $VPN_CLIENT_KEY"
        [ -n "$VPN_CA_FILE" ]      && echo "ca-file = $VPN_CA_FILE"
        [ -n "$VPN_SNI" ]          && echo "sni = $VPN_SNI"
        [ -n "$VPN_MIN_TLS" ]      && echo "min-tls = $VPN_MIN_TLS"
        echo "set-dns = $VPN_SET_DNS"
        echo "pppd-use-peerdns = $VPN_PPPD_PEERDNS"
        echo "half-internet-routes = $VPN_HALF_INTERNET_ROUTES"
        echo "insecure-ssl = $VPN_INSECURE_SSL"
        echo "persistent = 0"
    } > "$CONFIG_FILE"
    chmod 600 "$CONFIG_FILE"
}

# Keep the route to the VPN gateway on the physical uplink, otherwise the
# default route pushed through ppp0 would blackhole our own control channel.
pin_server_routes() {
    SERVER_IPS="$(resolve_ipv4 "$VPN_HOST")"
    if [ -z "$SERVER_IPS" ]; then
        warn "could not resolve $VPN_HOST, killswitch will only allow the configured port"
        return 0
    fi
    log "VPN gateway $VPN_HOST resolves to: $SERVER_IPS"
    local ip
    for ip in $SERVER_IPS; do
        if [ -n "$UPLINK_GW" ]; then
            ip route replace "$ip/32" via "$UPLINK_GW" dev "$UPLINK_DEV" 2>/dev/null \
                || warn "could not pin route to $ip via $UPLINK_GW"
        else
            ip route replace "$ip/32" dev "$UPLINK_DEV" 2>/dev/null \
                || warn "could not pin route to $ip on $UPLINK_DEV"
        fi
    done
}

setup_firewall() {
    log "installing killswitch firewall ($IPT)"
    # Start from a clean slate inside our own network namespace.
    $IPT -F            || warn "could not flush filter table"
    $IPT -t nat -F     || true
    $IPT -t mangle -F  || true
    $IPT -P INPUT ACCEPT
    $IPT -P OUTPUT DROP
    $IPT -P FORWARD DROP

    # Loopback and replies.
    $IPT -A INPUT  -i lo -j ACCEPT
    $IPT -A INPUT  -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    $IPT -A OUTPUT -o lo -j ACCEPT
    $IPT -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

    # All traffic that leaves through the tunnel is fine.
    $IPT -A OUTPUT -o ppp+ -j ACCEPT

    # Let clients on the local network reach this container (e.g. for DNS).
    $IPT -A INPUT -i "$LAN_IFACE" -j ACCEPT

    # Control channel to the VPN gateway on the physical uplink.
    local ip
    if [ -n "$SERVER_IPS" ]; then
        for ip in $SERVER_IPS; do
            $IPT -A OUTPUT -o "$LAN_IFACE" -d "$ip" -p tcp --dport "$VPN_PORT" -j ACCEPT
            $IPT -A OUTPUT -o "$LAN_IFACE" -d "$ip" -p udp --dport "$VPN_PORT" -j ACCEPT
        done
    else
        $IPT -A OUTPUT -o "$LAN_IFACE" -p tcp --dport "$VPN_PORT" -j ACCEPT
        $IPT -A OUTPUT -o "$LAN_IFACE" -p udp --dport "$VPN_PORT" -j ACCEPT
    fi

    # DNS on the physical uplink. This is deliberately allowed to any resolver:
    # Docker's embedded DNS forwarder (127.0.0.11) lives in this network
    # namespace and needs to reach the upstream resolvers itself, both to
    # resolve the gateway and while the tunnel is reconnecting.
    $IPT -A OUTPUT -o "$LAN_IFACE" -p udp --dport 53 -j ACCEPT
    $IPT -A OUTPUT -o "$LAN_IFACE" -p tcp --dport 53 -j ACCEPT

    # DHCP.
    $IPT -A OUTPUT -o "$LAN_IFACE" -p udp --dport 67 -j ACCEPT

    # Forwarded traffic (when the container is used as a real gateway).
    $IPT -A FORWARD -i ppp+ -o "$LAN_IFACE" -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    if [ -n "$LAN_SUBNET" ]; then
        $IPT -A FORWARD -s "$LAN_SUBNET" -o ppp+ -j ACCEPT
    else
        $IPT -A FORWARD -o ppp+ -j ACCEPT
    fi

    # NAT and TCP MSS clamping so forwarded traffic survives the small PPP MTU.
    $IPT -t nat -A POSTROUTING -o ppp+ -j MASQUERADE
    $IPT -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu \
        || warn "TCPMSS clamp not available"
    $IPT -t mangle -A OUTPUT -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu \
        || true
}

# ---------------------------------------------------------------------------
# Tunnel lifecycle
# ---------------------------------------------------------------------------
on_tunnel_up() {
    local iface="$1"
    log "tunnel is up on $iface"
    if is_on "$VPN_FULL_TUNNEL"; then
        ip route replace default dev "$iface" 2>/dev/null \
            && log "default route now points at $iface" \
            || warn "could not set default route via $iface"
    fi
    if [ -n "$DNS_SERVERS" ]; then
        { for ns in ${DNS_SERVERS//,/ }; do echo "nameserver $ns"; done; } > /etc/resolv.conf 2>/dev/null \
            || warn "could not write /etc/resolv.conf"
        log "using DNS servers: $DNS_SERVERS"
    fi
}

on_tunnel_down() {
    log "tunnel went down"
    # Restore the physical default route so DNS and the next reconnect attempt
    # keep working. The killswitch still blocks everything else.
    if [ -n "$UPLINK_DEV" ] && [ -n "$UPLINK_GW" ]; then
        ip route replace default via "$UPLINK_GW" dev "$UPLINK_DEV" 2>/dev/null || true
    fi
}

monitor_tunnel() {
    local pid="$1" iface
    while kill -0 "$pid" 2>/dev/null; do
        iface="$(current_ppp_iface)"
        if [ -n "$iface" ] && iface_has_ipv4 "$iface"; then
            if [ "$CONFIGURED_IFACE" != "$iface" ]; then
                CONFIGURED_IFACE="$iface"
                on_tunnel_up "$iface"
            fi
        elif [ -n "$CONFIGURED_IFACE" ]; then
            CONFIGURED_IFACE=""
            on_tunnel_down
        fi
        sleep 2
    done
}

run_once() {
    local args=(-c "$CONFIG_FILE")
    [ -n "$VPN_OTP" ] && args+=("--otp=$VPN_OTP")
    if [ -n "$VPN_EXTRA_ARGS" ]; then
        local extra
        read -r -a extra <<<"$VPN_EXTRA_ARGS"
        args+=("${extra[@]}")
    fi
    log "connecting to $VPN_HOST:$VPN_PORT as ${VPN_USER:-<no user>}"
    openfortivpn "${args[@]}" &
    VPN_PID=$!
    monitor_tunnel "$VPN_PID"
    wait "$VPN_PID"
    return $?
}

shutdown() {
    [ "$STOPPING" = 1 ] && return
    STOPPING=1
    log "shutting down"
    [ -n "$VPN_PID" ] && kill "$VPN_PID" 2>/dev/null
    wait "$VPN_PID" 2>/dev/null
    exit 0
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
[ "$(id -u)" = 0 ] || die "this container must run as root"

# Allow the image to be used as a normal base image too.
if [ "$#" -gt 0 ]; then
    exec "$@"
fi

[ -n "$VPN_HOST" ] || die "VPN_HOST is required"

VPN_PASSWORD="${VPN_PASSWORD:-$(read_file "$VPN_PASSWORD_FILE")}"
VPN_OTP="${VPN_OTP:-$(read_file "$VPN_OTP_FILE")}"

if is_on "$FIREWALL_ENABLED" && command -v iptables-legacy >/dev/null 2>&1; then
    IPT="iptables-legacy"
fi

detect_uplink || warn "no default route found; LAN_IFACE/forwarding may not work"
LAN_IFACE="${LAN_IFACE:-${UPLINK_DEV:-eth0}}"

create_ppp_device
enable_forwarding
write_config
pin_server_routes

if is_on "$FIREWALL_ENABLED"; then
    setup_firewall
else
    warn "killswitch firewall is disabled"
fi

trap shutdown TERM INT

while :; do
    run_once
    rc=$?
    CONFIGURED_IFACE=""
    [ "$STOPPING" = 1 ] && break
    log "openfortivpn exited (rc=$rc), reconnecting in ${VPN_RECONNECT_DELAY}s"
    sleep "$VPN_RECONNECT_DELAY"
done