"""Environment configuration, validation, and openfortivpn rendering."""

from __future__ import annotations

import ipaddress
from dataclasses import dataclass, field

from .runtime import DELAY_RE, PORT_RE, FatalError, split_list


@dataclass
class Config:
    host: str = ""
    port: int = 443
    user: str = ""
    password: str = ""
    password_file: str = ""
    otp: str = ""
    otp_file: str = ""
    realm: str = ""
    trusted_cert: str = ""
    client_cert: str = ""
    client_key: str = ""
    ca_file: str = ""
    sni: str = ""
    set_dns: str = "0"
    pppd_peerdns: str = "0"
    half_internet_routes: str = "0"
    insecure_ssl: str = "0"
    min_tls: str = ""
    set_routes: str = "1"
    full_tunnel: str = "on"
    routes: list[str] = field(default_factory=list)
    exclude_routes: list[str] = field(default_factory=list)
    reconnect_delay: float = 5.0
    extra_args: str = ""
    firewall_enabled: str = "on"
    lan_iface: str = ""
    lan_subnet: str = ""
    dns_servers: str = ""
    config_file: str = "/etc/openfortivpn/config"

    @classmethod
    def from_env(cls, env: dict[str, str]) -> Config:
        def get(key: str, default: str = "") -> str:
            return env.get(key, default)

        cfg = cls(
            host=get("VPN_HOST"),
            user=get("VPN_USER"),
            password=get("VPN_PASSWORD"),
            password_file=get("VPN_PASSWORD_FILE"),
            otp=get("VPN_OTP"),
            otp_file=get("VPN_OTP_FILE"),
            realm=get("VPN_REALM"),
            trusted_cert=get("VPN_TRUSTED_CERT"),
            client_cert=get("VPN_CLIENT_CERT"),
            client_key=get("VPN_CLIENT_KEY"),
            ca_file=get("VPN_CA_FILE"),
            sni=get("VPN_SNI"),
            set_dns=get("VPN_SET_DNS", "0"),
            pppd_peerdns=get("VPN_PPPD_PEERDNS", "0"),
            half_internet_routes=get("VPN_HALF_INTERNET_ROUTES", "0"),
            insecure_ssl=get("VPN_INSECURE_SSL", "0"),
            min_tls=get("VPN_MIN_TLS"),
            set_routes=get("VPN_SET_ROUTES", "1"),
            full_tunnel=get("VPN_FULL_TUNNEL", "on"),
            routes=split_list(get("VPN_ROUTES")),
            exclude_routes=split_list(get("VPN_EXCLUDE_ROUTES", "100.64.0.0/10")),
            extra_args=get("VPN_EXTRA_ARGS"),
            firewall_enabled=get("FIREWALL_ENABLED", "on"),
            lan_iface=get("LAN_IFACE"),
            lan_subnet=get("LAN_SUBNET"),
            dns_servers=get("DNS_SERVERS"),
            config_file=get("CONFIG_FILE", "/etc/openfortivpn/config"),
        )
        port_raw = get("VPN_PORT", "443")
        if not PORT_RE.match(port_raw) or not 1 <= int(port_raw) <= 65535:
            raise FatalError("VPN_PORT must be an integer from 1 to 65535")
        cfg.port = int(port_raw)
        delay_raw = get("VPN_RECONNECT_DELAY", "5")
        if not DELAY_RE.match(delay_raw):
            raise FatalError("VPN_RECONNECT_DELAY must be a non-negative number")
        cfg.reconnect_delay = float(delay_raw)
        if not cfg.host:
            raise FatalError("VPN_HOST is required")
        if cfg.password and cfg.password_file:
            raise FatalError("set only one of VPN_PASSWORD and VPN_PASSWORD_FILE")
        if cfg.otp and cfg.otp_file:
            raise FatalError("set only one of VPN_OTP and VPN_OTP_FILE")
        if cfg.set_routes not in ("0", "1"):
            raise FatalError("VPN_SET_ROUTES must be 0 or 1")

        def normalize_ipv4_cidrs(cidrs: list[str]) -> list[str]:
            normalized = []
            for cidr in cidrs:
                try:
                    network = ipaddress.ip_network(cidr, strict=False)
                except ValueError:
                    raise FatalError(
                        f"invalid CIDR in VPN_ROUTES/VPN_EXCLUDE_ROUTES: {cidr}"
                    )
                if network.version != 4:
                    raise FatalError(
                        f"only IPv4 CIDRs are supported in VPN_ROUTES/"
                        f"VPN_EXCLUDE_ROUTES: {cidr}"
                    )
                normalized.append(str(network))
            return normalized

        cfg.routes = normalize_ipv4_cidrs(cfg.routes)
        cfg.exclude_routes = normalize_ipv4_cidrs(cfg.exclude_routes)
        return cfg


def render_config(cfg: Config) -> str:
    lines = [
        "# generated by the openfortivpn entrypoint",
        f"host = {cfg.host}",
        f"port = {cfg.port}",
    ]
    optional = [
        ("username", cfg.user),
        ("password", cfg.password),
        ("otp", cfg.otp),
        ("realm", cfg.realm),
        ("trusted-cert", cfg.trusted_cert),
        ("user-cert", cfg.client_cert),
        ("user-key", cfg.client_key),
        ("ca-file", cfg.ca_file),
        ("sni", cfg.sni),
        ("min-tls", cfg.min_tls),
    ]
    lines += [f"{key} = {val}" for key, val in optional if val]
    lines += [
        f"set-dns = {cfg.set_dns}",
        f"pppd-use-peerdns = {cfg.pppd_peerdns}",
        f"half-internet-routes = {cfg.half_internet_routes}",
        f"insecure-ssl = {cfg.insecure_ssl}",
        f"set-routes = {cfg.set_routes}",
        "persistent = 0",
    ]
    return "\n".join(lines) + "\n"
